### ISSUE TITLE
Output intensity_image for each label

### ISSUE THREAD

**Issue by evangeline-corcoran** [alan-turing-institute/pixelflow#36]
For the seed use case, it would be ideal if the `intensity_image` for each labelled object in a mask could be automatically saved as a numpy array, and named based on the label number to allow matching between the image + features table values. In this use case the `intensity_image` gives a segmented array of an individual seed which is useful for further analysis (e.g. VAE, clustering to explore factors affecting seed internal structure).

The segmented image (`intensity_image`) of a single seed can be created with `regionprops` and saved as an numpy array as below:

```
import numpy
import skimage

props = skimage.measure.regionprops(labels[0], img[0], cache=True)

seed_array = props[0].intensity_image
seed_array

numpy.save("/content/gdrive/MyDrive/Example CT Data/C0007864_seed4.npy", seed_array)
```

**Comment by IFenton** [comment]
At the moment you should be able to get the image_intensity numpy array by including 'image_intensity' in the features list. If you save the result, you can then access the arrays by using result.image_intensity (rather than result.features for the features dataframe). The individual arrays are not explicitly named, but they are output in the same order as the feature table and can be accessed using indexing. Does that solve your problem for the moment?

**Comment by evangeline-corcoran** [comment]
If there is a way to generate all the features + intensity images with pixelflow at once but avoid the intensity_image arrays being included in the table I need to export as csv  I think that would be an improvement, but keeping this separate works fine

**Comment by evangeline-corcoran** [comment]
A slight correction: As you suggested we can just use `results.image_intensity` to retrieve the images for each label rather than `results.features.intensity_image` as shown in the example below

```
#generate segmented images of each individual seed in a mask
seg_seed = pixelflow(
    mask,
    img,
    features=('label', 'image_intensity')
)

#make list of all seeds in mask, shift backwards by one to match index values
X = list(seg_seed.features.label)
for i in range(len(X)):
    X[i] -= 1

#save segmented images of all seeds within a seed pod
for file in X:
    np.save(pod_name + '_seed_' + str(seg_seed.features.label[file]) + '.npy', seg_seed.image_intensity[file])
```

**Comment by IFenton** [comment]
The latest merges mean that the image_intensity can be extracted from both 2D and 3D images as part of a list of features.
